#! /bin/bash

username="ammar"
groupname="ammar"


if [[ $( cat /etc/passwd | grep ammar | cut -d: -f1) = ammar ]]
then 
	echo "this user exists:"
	echo $( cat /etc/passwd | grep ammar)
else
	useradd ammar
	echo $( cat /etc/passwd | grep ammar)
fi


if [[ $( cat /etc/group | grep ammar | cut -d: -f1) = ammar ]]
then  
	echo "this group exists:"
	echo $( cat /etc/group | grep ammar)
else
	groupadd ammar
	echo $( cat /etc/group | grep ammar)
fi
